name: arweave update

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  curl:
      runs-on: ubuntu-latest
      steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: -m 86400 https://web3index-org-og7jyfbi9-livepeerorg.vercel.app/api/cron/arweave
